# Generated by Django 3.2 on 2023-03-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turmeric', models.IntegerField()),
                ('chilli', models.IntegerField()),
                ('coriander', models.IntegerField()),
            ],
        ),
    ]
