# Generated by Django 3.2 on 2023-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res.cloudinary.com/dlprc6hdu/image/upload/v1673549153/vxiqpa8mdocjfm3hij4k.jpg', upload_to='images/'),
        ),
    ]
