# Generated by Django 3.2 on 2023-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utensils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensils',
            name='cup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utensils',
            name='plate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='utensils',
            name='spoon',
            field=models.IntegerField(),
        ),
    ]
