# Generated by Django 3.2 on 2023-03-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipeposts', '0002_auto_20230317_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='pic_filter',
            field=models.CharField(choices=[('_2017', '2017'), ('bran', 'Bran'), ('spoon', 'Spoon'), ('fork', 'Fork'), ('bowl', 'Bowl'), ('plate', 'Plate')], default='normal', max_length=32),
        ),
    ]
