# Generated by Django 3.2 on 2023-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipeposts', '0003_auto_20230317_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='pic',
            field=models.ImageField(default='../default_post_rgq6aq', upload_to='images/'),
        ),
    ]
